variable "tf_lbl_cost_center" {}
variable "tf_lbl_product" {}
variable "tf_lbl_deployment_name" {}
variable "tf_lbl_owner" {}
variable "tf_lbl_environment" {}
variable "tf_lbl_provisioned_by" {}
variable "tf_lbl_source_repo" {}
variable "tf_lbl_releaseid" {}
variable "tf_lbl_buildid" {}
variable "resource_group" {}
variable "location" {}
variable "eventgrid" {}
variable "eventgridsubscription" {}
variable "storageaccount" {}
variable "subscriptionkey" {}
